### ISSUE TITLE
SERMAS toolkit permissions on Win10

### ISSUE THREAD

**Issue by nevessilva31** [sermas-eu/sermas-eu.github.io#3]
Hi,
I was following the step-by-step instructions at: https://sermas-eu.github.io/docs/create-application
and the steps are not performing as expected. I'm running the demo on **Windows 10**. 

After the command 
**sermas-cli app init /apps/myapp**
I am getting the error:
**error: Failed to create template EACCES: permission denied, mkdir '/cli/C:'**
I have tried everything related with setting permissions without success.
Can you help me pass this step, please?

Thanks a lot,
Rui

**Comment by lc-spxl** [comment]
Hello, thank you for reporting. 

We do not have much testing yet on Windows so it may be the guide need to be updated (and a PR would be welcome :) ).

The path looks wrong.  Are you running it from the container or as plain npm module ?

**Comment by nevessilva31** [comment]
Hi Luca,
Thank you for your prompt reply.
After I run:
git clone https://github.com/sermas-eu/sermas-toolkit-api
using git bash command window
the sermas-toolkit-api folder gets installed at my user directory (in my case: C:\Users\rnspr\sermas-toolkit-api)
Then I've proceeded at git bash with the rest of the commands

**Comment by lc-spxl** [comment]
Sounds good,
we definitely still need to test it on Window. It's working on linux and maybe could also work on a WSL subsystem (?)

I would you suggest to wait for us to test on windows, or go on and report the issues you found, depending on your availability. 

The steps are in order:  

1. you should have the API running as described here https://sermas-eu.github.io/docs/getting-started
2. alias the CLI via docker as described here https://sermas-eu.github.io/docs/create-application
3.  continue with the tutorial

Thanks!

**Comment by nevessilva31** [comment]
I have tried with WSL but the docker is not recognizing it... 
I would like to understand the real possibilities of the toolkit to prepare a project proposal to the SERMAS Open Call #2 closing on June,26 and I understood that it is supposed that we should use the SERMAS-toolkit.
Thanks,

**Comment by lc-spxl** [comment]
Yes I understand. 
It's a bit difficult to support you via github, we have a discord chat where we may spend some more time https://discord.com/channels/1222607234547191869/1222607234547191872

In the meanwhile, you could have a look here for PoCs https://prod.sermas.spindoxlabs.it/  and check the APIs at 

- https://prod.sermas.spindoxlabs.it/api/swagger
- https://prod.sermas.spindoxlabs.it/api/async

We will also have webinar in the next days, here more info https://www.linkedin.com/company/sermas-eu/

Thank you!

**Comment by anto9991** [comment]
Hi,
we updated the guide to support Windows users (note that WSL is required);
please let us know if there are any other issues.
Thanks,
Gabriel.

**Comment by lc-spxl** [comment]
Please reopen if it still applies

**Comment by nevessilva31** [comment]
Hi Luca and Gabriel,

I have been all day around this error - WSL print: [with admin as password]:
---------
rnspr@pc-rns:/mnt/c/Users/rnspr/sermas-toolkit-api$ sermas-cli auth login admin
WARN[0000] /mnt/c/Users/rnspr/sermas-toolkit-api/docker-compose.yaml: `version` is obsolete
? Your password [hidden]
**error: Request failed: Bad Gateway
error: Login failed**
-----------
Do you have any idea why this might be happening?

I deleted everything and started all over several times already following your guideline without success :-( It worked before, although I never got to access the openai model.

Thank you for your support,

Rui

**Comment by lc-spxl** [comment]
I would say the API is not running,  could you check if there are errors in `docker compose logs api`. Post here the output in case thank you

**Comment by nevessilva31** [comment]
The mongo database keeps exiting immediately after start. On Jun 7, 2024 07:37, Luca Capra ***@***.***> wrote:
I would say the API is not running,  could you check if there are errors in docker compose logs api. Post here the output in case thank you

**Comment by lc-spxl** [comment]
Without the logs it's difficult to get what is going on. Please let's take some time to sort this out here https://discord.com/channels/1222607234547191869/1248525462351642689

**Comment by tiagorribeiro24** [comment]
I've also had this permissions error on Ubuntu 24.04. Whenever it tried to save the credentials in a file (`sermas-cli auth login admin` command and pressed -y for saving it) or when trying to create a folder with mkdir (`sermas-cli app init /apps/myapp` command). 
 What I did was to add a `sudo` command before the docker compose run on the alias command: 
```
alias "sermas-cli=sudo docker compose run --rm -it --user `echo $UID` cli"
```
